### ISSUE TITLE
Duplicate tweets in feed

### ISSUE THREAD

**Issue by TheHCJ** [TheHCJ/Quacker#1]
## Might be fixed in latest beta
**Please reply if it is fixed for you**

### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TheHCJ/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TheHCJ/quacker/issues) or [closed](https://github.com/TheHCJ/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Quacker

### Affected version

3.0.0

### Steps to reproduce the bug

1. Go to feed
2. See duplicate tweets

### Expected behavior

No duplicate tweets should appear

### Actual behavior

Duplicate tweets appear

### Affected Android/Custom ROM version

Android 13

### Affected device model

Nokia C32

**Comment by TheHCJ** [comment]
Fixed: https://github.com/TheHCJ/Quacker/actions/runs/5591850352

**Comment by nannadroid** [comment]
This problem still exists. Can I reopen this issue or should I create new issue? (screenshot taken is shown inactive when tried to attach)

**Comment by nannadroid** [comment]
> This problem still exists. Can I reopen this issue or should I create new issue? (screenshot taken is shown inactive when tried to attach)
> 
> Version details: { "abis": [ "arm64-v8a", "armeabi-v7a", "armeabi" ], "device": "OnePlus6", "locale": "en", "os": "android", "system": "30", "version": "4" }

@TheHCJ this still exists, and I am not allowed to create new issue if there is existing issue (open/closed). Version detail added above (v3.0.0.+4)

**Comment by nannadroid** [comment]
I'm unable to attach files, any idea why? (I confirmed media permission is provided)

**Comment by nannadroid** [comment]
> > This problem still exists. Can I reopen this issue or should I create new issue? (screenshot taken is shown inactive when tried to attach)
> > Version details: { "abis": [ "arm64-v8a", "armeabi-v7a", "armeabi" ], "device": "OnePlus6", "locale": "en", "os": "android", "system": "30", "version": "4" }
> 
> @TheHCJ this still exists, and I am not allowed to create new issue if there is existing issue (open/closed). Version detail added above (v3.0.0.+4)

An additional hint: this is random behavior - some posts are duplicated and some are not

**Comment by TheHCJ** [comment]
Does this also occur in the ci build?

**Comment by nannadroid** [comment]
Yes, this was from ci build (but app still shows 3.0.0+4). To confirm, I just now uninstalled the app and installed the [latest](https://github.com/TheHCJ/Quacker/actions/runs/5701505632) ci build. I still see the issue (somehow I'm unable to upload the screenshots; all the pics are shown inactive).

**Comment by nannadroid** [comment]
![Screenshot_20230801-170032](https://github.com/TheHCJ/Quacker/assets/113890947/039e86ff-a2f0-4ef0-b8ec-e793224f33f4)
![Screenshot_20230801-170057](https://github.com/TheHCJ/Quacker/assets/113890947/19d3b802-3cce-40a8-99be-0feeb320971b)

I now see triplication of tweets!! Quacker version not changed (at least explicitly; not sure if silent update happened).

**Comment by TheHCJ** [comment]
I think I have fixed it, I will leave this issue open incase I am wrong

**Comment by nannadroid** [comment]
> I think I have fixed it, I will leave this issue open incase I am wrong

Is the ci build available? I can test it

**Comment by TheHCJ** [comment]
Here: https://github.com/TheHCJ/Quacker/suites/14754918188/artifacts/838833609

**Comment by nannadroid** [comment]
Have been using the new build for two days now. Haven't yet observed duplications. Will notify the status again in couple of days here.

**Comment by TheHCJ** [comment]
Oh ok

**Comment by TheHCJ** [comment]
As there is no more feedback in regards to this issue, I will be closing it until further notice
