### ISSUE TITLE
[BUG] Feed error

### ISSUE THREAD

**Issue by AndiDink00x** [TheHCJ/Quacker#1]
A get again the known error on feed , by deleting storage data fixes the issue temporarily

Using LineageOS 19.1 
Android 12L

**Comment by AndiDink00x** [comment]
> HJC's previous build, with all the fritter branding still works perfectly though.

Yeah im still using @TheHCJ fritter apk because it still works

**Comment by TheHCJ** [comment]
I am now working on a fix
