### ISSUE TITLE
[BUG] Display blue check users in feed

### ISSUE THREAD

**Issue by AndiDink00x** [TheHCJ/Quacker#12]
**Describe the bug**
The blue check on users that have it is properly displayed on their account wall but not in the feed tab

**Expected behavior**
Blue check in users should be displayed properly as in their account page

**Screenshots**
Account page blue check properly displayed: https://imgur.com/a/dWVwmau
Missing blue check in feed: https://imgur.com/a/IoNjt3j

**System Infomation (please complete the following information):**
 - OS: LineageOS 19.1 , Poco x3 Pro , Android 12.1
 - Version: latest ci build 4.0.0 beta 1 - https://github.com/TheHCJ/Quacker/commit/d63355cb1b2901b41e1e28fdf3304b70c8809639

**Additional context**
This feature was already present before the API changes

**Comment by TheHCJ** [comment]
This is currently unfixable as the search api doesn't return if a user is verified. I will look into this once the GraphQL endpoints are fixed.
