### ISSUE TITLE
[BUG] F-Droid - disable autoupdate check by default

### ISSUE THREAD

**Issue by licaon-kter** [TheHCJ/Quacker#18]
Is is enough to make https://github.com/TheHCJ/Quacker/blob/v3.4.0/lib/main.dart#L158 `false` ?

**Comment by TheHCJ** [comment]
Yes, I'll make sure to do that for the F-Droid build

**Comment by TheHCJ** [comment]
@licaon-kter I should of fixed this

**Comment by TheHCJ** [comment]
This issue has been fixed in [v3.4.1](https://github.com/TheHCJ/Quacker/releases/tag/v3.4.1)

**Comment by licaon-kter** [comment]
Nice
