### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anton-isidore** [TheHCJ/Quacker#19]
**Describe the bug**
Cannot install via [Obtainium](https://github.com/ImranR98/Obtainium) due to version mismatch

**To Reproduce**
1. Install version 2.0.0
2. Try to update with Obtainium

**Screenshots**
- https://ibb.co/fCHfL3C
- https://ibb.co/Yk2V61w

**Device**
Irelevant

**Does this bug affect fritter?**
No

**Comment by TheHCJ** [comment]
Sorry about this, I think I forgot to update the package name. Should be fixed now 😃
