### ISSUE TITLE
[BUG] Video player not working

### ISSUE THREAD

**Issue by AndiDink00x** [TheHCJ/Quacker#2]
Video player doesnt work

using **0.2** version
LineageOS 19.1
Android 12L

1. Also amoled theme is not available ☹️☹️ can you bring it back pls 
2. Blue checks do not appear
3. UI on search bar is bugged

**Comment by TheHCJ** [comment]
Looks like I have duplicate code! 🧑‍💻
I will work on a fix for today's nightly release. 🌑
