### ISSUE TITLE
"Sensitive" tweets are not visible

### ISSUE THREAD

**Issue by Snyret** [TheHCJ/Quacker#2]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TheHCJ/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TheHCJ/quacker/issues) or [closed](https://github.com/TheHCJ/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Quacker

### Affected version

3.0.0

### Steps to reproduce the bug

1. Going to any tweet that's age restricted

**Comment by TheHCJ** [comment]
NSFW tweets currently aren't viewable due to twitter limitations. Check out https://github.com/jonjomckay/fritter/issues/658
Otherwise enable sensitive tweets in settings
