### ISSUE TITLE
[BUG] App data loss (or data not loading) on version upgrade

### ISSUE THREAD

**Issue by Hameree** [TheHCJ/Quacker#21]
**Describe the bug**
After upgrating from version 2 to version 2.1.0, all data was lost including subscriptions, group members, etc.

**To Reproduce**
1. Install Quacker version 2 for the first time
2. Import previous data from fritter, use as normal for about a week
3. Update to v2.1.0 (downloaded `fritter-v2.1.0_armeabi-v7a.apk` for my device)
2. Open the app, notice all data was lost
4. Restart the device, nothing changed
5. Export data to try to recover it, but notice it didn't export my data at all (only default settings):

```json
{"settings":{"media.mute":false,"disable_screenshots":false,"other.improve_non_confirmation_bias":false,"trends.locations":"{\"active\":{\"name\":\"Worldwide\",\"woeid\":1,\"country\":null,\"countryCode\":null,\"parentid\":null,\"url\":null,\"placeType\":null},\"locations\":[{\"name\":\"Worldwide\",\"woeid\":1,\"country\":null,\"countryCode\":null,\"parentid\":null,\"url\":null,\"placeType\":null}]}","subscription.order_by.ascending":true,"subscription.order_by.field":"screen_name","download.type":"ask","should_check_for_updates":true,"home.pages":["feed","subscriptions","groups","trending","saved"],"theme.material3":true,"theme.color_scheme":"bahamaBlue","trends.location":"{\"name\":\"<redacted>\",\"woeid\":<redacted>,\"country\":\"<redacted>\",\"countryCode\":\"<redacted>\",\"parentid\":1,\"url\":\"http://where.yahooapis.com/v1/place/<redacted>\",\"placeType\":{\"code\":12,\"name\":\"Country\"}}","theme.true_black":true,"subscription_groups.order_by.ascending":false,"home.initial_tab":"groups","subscription_groups.order_by.field":"name","errors.sentry_enabled":false,"download.path":"","media.size":"medium","theme.mode":"dark","locale":"system","tweets.hide_sensitive":false},"searchSubscriptions":[],"subscriptions":[],"subscriptionGroups":[],"subscriptionGroupMembers":[],"tweets":null}
```

6. To see whether my data is possibly still there, here is my device's current storage usage:  

Quacker version 2.1.0:  
App: 40.88 MB  
Data: 25.72 MB  
Cache: 92.34 MB  
Total: 159 MB  

Fritter version 3.0.0-beta7 (with about a week of nonusage since I installed Quacker, meaning there could be a few more or less subcriptions, etc.):  
App: 41.94 MB
Data: 16.95 MB
Cache: 20.80 MB
Total: 79.69 MB

**Device**
Devicel model/number: Samsung A10 / SM-A105M  
OS version: Android 11. One UI version: 3.1 (stock OS)  
Device locale/language: English (United States) 
Quacker version: 2.1.0 (`fritter-v2.1.0_armeabi-v7a.apk`)

**Does this bug affect fritter?**
Don't Know (but this never happened with fritter)

**Comment by alanpoulain** [comment]
It's because the database has been renamed from `fritter.db` to `quacker.db`.
Fortunately, your data have not been lost.

**Comment by TheHCJ** [comment]
This is the case, I will add this as a note in the desciption of the release!
