### ISSUE TITLE
[REQ]  Add PanicKit support

### ISSUE THREAD

**Issue by grrrrr** [TheHCJ/Quacker#24]
**Describe the problem that needs solving**

I am working in and with people in countries where the governments and police are not friendly to them and certain lifestyles are seen as morally wrong and if phones are confistated and you are found with accessing such material it can land you in serious trouble.    It would be very useful in an emergency to clear the accounts that you follow in Quacker

**Describe the solution you'd like**

It would be really useful to have [PanicKit](https://github.com/guardianproject/PanicKit) support added to the `Quacker` android app

This would allow the user to trigger (e.g. with [Ripple](https://github.com/guardianproject/ripple)) a destructive or non destructive response in a "panic" situation where a device may be at risk of being taken and being used to access data stored by `Quacker`

More details on PanicKit: https://guardianproject.info/code/panickit/

**Comment by TheHCJ** [comment]
It isn't possible in flutter at the momment, I am looking into other solutions
