### ISSUE TITLE
[REQ] Add data encryption of database

### ISSUE THREAD

**Issue by grrrrr** [TheHCJ/Quacker#25]
**Describe the problem that needs solving**

An additional request tied to issue #24    Hopefully adding an additional layer of data protection to user of Quacker

**Describe the solution you'd like**

I'd like to suggest the use of [SQLCipher](https://github.com/sqlcipher/sqlcipher) within the app, it's a fork of SQLite and should hopefully be mostly a drop in replacement.   This would add a layer of protection to the data the app holds

**Comment by TheHCJ** [comment]
I am working on this to be published in the next minor release 2.2.0

**Comment by TheHCJ** [comment]
I am looking into this, keep your eyes peeled for updates

**Comment by TheHCJ** [comment]
Please create this issue in fritter instead
https://github.com/jonjomckay/fritter/issues/new/choose
