### ISSUE TITLE
Inconsistent App name

### ISSUE THREAD

**Issue by momobobe** [TheHCJ/Quacker#28]
Not really a bug, just somewhere it still uses Fritter instead of Quacker in app, like when exiting the app it shows "Are you sure you want to close Fritter?" Not a big issue, but you may want to do a global search for string "Fritter".

**Comment by j-fbriere** [comment]
The most recent version 2.1.1 have removed Fritter from the messages but have not replaced it by Quacker.
Here is the fix.
[fix_28.patch](https://github.com/TheHCJ/Quacker/files/11519882/fix_28.patch)

**Comment by TheHCJ** [comment]
Now merged!

**Comment by j-fbriere** [comment]
After the patch applied, @TheHCJ, you must execute
flutter pub run intl_utils:generate
and then commit the generated files.

Why commit the generated files? 
It's better when we want to debug the app.

**Comment by j-fbriere** [comment]
I checked the merged lib/l10n/*.arb files and I don't think that the merge worked.

I tried to patch with the file I provided and indeed it did not work.
Here is the corrected file, sorry:
[fix_28_2.patch](https://github.com/TheHCJ/Quacker/files/11520657/fix_28_2.patch)

Then you patch it with the following command from the Quacker root folder:
`git apply --ignore-space-change --ignore-whitespace fix_28_2.patch`

After the patch applied, you must execute
`flutter pub run intl_utils:generate`
and then commit the generated files located under **lib/generated**.

**Comment by TheHCJ** [comment]
Thank you for the update, I was wondering why I got an error every time I attempted to commit the patch files

**Comment by TheHCJ** [comment]
This will release with v2.2.0 later today
