### ISSUE TITLE
[BUG]please fix

### ISSUE THREAD

**Issue by Twig6943** [TheHCJ/Quacker#3]
My device is huawei y6 2019 and the feed tab doesnt work when I deselect the retweets+answers.

> https://imgur.com/a/Vi6KSCA
https://imgur.com/a/ql9sZ4G

**Comment by TheHCJ** [comment]
What version of Quacker are you running?

**Comment by Twig6943** [comment]
Latest

**Comment by Twig6943** [comment]
Also @TheHCJ regardless of the bug tysm for making this fork <3

**Comment by TheHCJ** [comment]
Could you take a screenshot of the about page?

**Comment by Twig6943** [comment]
Update 0.2 did seem to fix the issue but please bring back the removed features
