### ISSUE TITLE
[BUG] 2.1.1 - Quote and long tweets

### ISSUE THREAD

**Issue by AndiDink00x** [TheHCJ/Quacker#30]
After update i seet that https://github.com/TheHCJ/Quacker/issues/14 and https://github.com/TheHCJ/Quacker/issues/7 are not fixed on Feed but i see that https://github.com/TheHCJ/Quacker/issues/7 fixed only in twitter accounts wall

using **2.1.1** version
LineageOS 19.1
Android 12L

**EDIT**: deleted claim for group tab bug

**Comment by TheHCJ** [comment]
Oops... Now making a new release to remedy the version not being correct. I have reopened the Issues while I get to fixing.

**Comment by TheHCJ** [comment]
I have closed this issue, I am still actively working on fixed to #7 and #14.

**Comment by AndiDink00x** [comment]
Thank you! I think these bugs are the last for app to be properly functional
