### ISSUE TITLE
[FEATURE REQUEST] Add share account in profile view

### ISSUE THREAD

**Issue by anyone00** [TheHCJ/Quacker#34]
**Is your feature request related to a problem? Please describe.**
Currently when viewing a profile the username is not selectable and there is no share functionality.

**Describe the solution you'd like**
Making users names user selectable would go a long way but adding a share button would be even better.

**Describe alternatives you've considered**
I can share a copy a link to a tweet then remove the specific tweet id part and keep the username.

**Additional context**
Imported from https://github.com/j-fbriere/squawker/issues/33

**Comment by TheHCJ** [comment]
I will start work on this as it doesn't seem to hard to add

**Comment by TheHCJ** [comment]
this issue will be fixed in the next release
