### ISSUE TITLE
versionCode "missing"

### ISSUE THREAD

**Issue by IzzySoft** [TheHCJ/Quacker#35]
Yould you please change [this line in `pubspec.yaml`](https://github.com/TheHCJ/Quacker/blob/master/pubspec.yaml#L18) to have it include the versionCode – and always increase it with new releases? Else Flutter defaults to `1`, so for Android it looks like the app is never updated. For starters, with today's release it should have been:

```yaml
version: 2.1.1+4
```

(as there were already 3 previous releases). You can use it as "release counter", or increase by other means – important is just it's an integer and always increased :wink: Thanks!

**Comment by TheHCJ** [comment]
Fixed, hope the app can be updated in the next refresh.

P.S Also can you remove the donation links and tracking label as they are
from fritter and not from Quacker

**Comment by IzzySoft** [comment]
> Fixed, hope the app can be updated in the next refresh.

Will have effect only starting with the next release (please remember increasing then). As the current one was already published, the updater won't replace it.

> Also can you remove the donation links and tracking label as they are from fritter and not from Quacker

Those came via `FUNDING.yaml`. As you removed it here, thanks to your pointer I've also removed it here. This change will be reflected with the next index update, i.e. around 6 pm UTC.

Thanks for the quick response & action!

**Comment by TheHCJ** [comment]
I will publish a release before 6pm UTC today

**Comment by TheHCJ** [comment]
Just made a release, for 5pm UTC

**Comment by IzzySoft** [comment]
Wonderful! Then it should be picked up by my updater and become available around 6 pm UTC. Thanks a lot! If there are any other open questions, just let me know.
