### ISSUE TITLE
[FEATURE REQUEST] Follow current theme color for translate icon

### ISSUE THREAD

**Issue by anyone00** [TheHCJ/Quacker#35]
**Is your feature request related to a problem? Please describe.**
Currently the translate icon in the timeline view is always blue no matter what the theme is selected.

Also when the like, retweet, replies numbers are big it goes outside the view a little bit. Maybe we can reduce the spacing a little bit to fit them all.

![Tweet view in Quacker](https://github.com/TheHCJ/Quacker/assets/41706133/de9f0091-f8ef-4256-aaa2-d94acfce1c0e)

**Describe the solution you'd like**
Follow the selected theme for translate button.

It would be a nice option to even hide the translate button because I never needed it. Sometimes I accidentally press it and it does not even work.

**Describe alternatives you've considered**
N/A

**Additional context**
Imported from https://github.com/j-fbriere/squawker/issues/34

**Comment by TheHCJ** [comment]
I'm fixing this issue

**Comment by TheHCJ** [comment]
fixed in the next release

**Comment by anyone00** [comment]
Thank you for working on them :blush:
