### ISSUE TITLE
[BUG] Invisible text in profile page light mode

### ISSUE THREAD

**Issue by anyone00** [TheHCJ/Quacker#37]
**Describe the bug**
When using light mode and visiting a profile page like https://x.com/firefox_es the bio text and the buttons are invisible.

**To Reproduce**
1. Go to settings and apply light mode
2. Go to [@firefox_es](https://x.com/firefox_es) profile

**Expected behavior**
The color for the bio text and and buttons should be opposite of the background to make it readable.

**Screenshots**
![Profile bio and buttons being invisible](https://github.com/TheHCJ/Quacker/assets/41706133/26fae4b1-283a-4aa7-8d13-98dc16e60069)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 14
 - Version: 3.4.3

**Additional info**
In dark mode it works as expected.

**Comment by TheHCJ** [comment]
I have fixed this issue for the next release
