### ISSUE TITLE
[REQ]  provide arm64-v8a builds on Izzy

### ISSUE THREAD

**Issue by grrrrr** [TheHCJ/Quacker#37]
**Describe the problem that needs solving**

Quacker is only available with armeabi-v7a.apk  it would be nice to have also the arm64-v8a.apk option for installing

**Comment by TheHCJ** [comment]
I am working on shrinking the app down so I can fit the apk within the 30mb limit. Once I have their will be support for all CPU's.

**Comment by grrrrr** [comment]
Nice.   I didn't realize the size limitation
