### ISSUE TITLE
[FEATURE REQUEST] Search specific accounts

### ISSUE THREAD

**Issue by anyone00** [TheHCJ/Quacker#38]
**Is your feature request related to a problem? Please describe.**
Not a specific problem, just a convenient button to search a profile

**Describe the solution you'd like**
The solution is already available in https://github.com/j-fbriere/squawker/commit/57d23b92d41fcba746bd1b0d00290c8acb9ee7a9

**Describe alternatives you've considered**
The alternative is to search manually and put the username in the query.

**Additional context**
It is already implemented in Squawker in [this commit](https://github.com/j-fbriere/squawker/commit/57d23b92d41fcba746bd1b0d00290c8acb9ee7a9)

**Comment by TheHCJ** [comment]
I have also implemented this for the next release
