### ISSUE TITLE
[REQ] expanding profile pictures

### ISSUE THREAD

**Issue by grrrrr** [TheHCJ/Quacker#40]
**Describe the problem that needs solving**

It would be useful if the ability to show a larger profile picture of accounts as you can with the website

**Describe the solution you'd like**

* Open a user profile
* Tap on users profile pic
* it opens larger (similar to pics in user posts)
* swipe to close large version of profile pic

**Comment by TheHCJ** [comment]
I will be working on this for the next release of Quacker.

**Comment by TheHCJ** [comment]
Please report this in fritter
https://github.com/jonjomckay/fritter/issues/new/choose
