### ISSUE TITLE
[REQ] Add a 'Share' action in selected text context menu

### ISSUE THREAD

**Issue by scubajeff** [TheHCJ/Quacker#42]
**Describe the problem that needs solving**
There are only two actions listed in selected text context menu, e.g., Copy and Select All

**Describe the solution you'd like**
Would like to have a 'Share' action in selected text context menu to share the text to another app, like a dictionary or wikipedia. Or even better, allow custom actions in context menu by adding the following to Manifest, if Flutter supports:
```
<!-- Place inside the <queries> element. -->
<intent>
  <action android:name="android.intent.action.PROCESS_TEXT" />
  <data android:mimeType="text/plain" />
</intent>
```

**Comment by TheHCJ** [comment]
This sounds like an easy thing to do. I will code something up soon to add this!

**Comment by scubajeff** [comment]
Thank you very much! The app is true saver.

**Comment by TheHCJ** [comment]
Please report this in fritter
https://github.com/jonjomckay/fritter/issues/new/choose
