### ISSUE TITLE
[REQ] Automatic backup

### ISSUE THREAD

**Issue by demolg** [TheHCJ/Quacker#44]
**Describe the problem that needs solving**
Manual backup is inconvenient. Please add feature to backup automatically.

**Describe the solution you'd like**
👇 eg: Tachiyomi( An comic app)
![Screenshot_20230526-092936_Animiru](https://github.com/TheHCJ/Quacker/assets/26198098/f9208c5a-7dca-430a-a3eb-9527955085ab)

**Comment by grrrrr** [comment]
Beat me to creating this ticket :)    It would be super useful.  Especially setting a default backup location

**Comment by TheHCJ** [comment]
I'll look into this, seems like it could be handy for some people

**Comment by TheHCJ** [comment]
Please report this in fritter
https://github.com/jonjomckay/fritter/issues/new/choose
