### ISSUE TITLE
No profile pics and names

### ISSUE THREAD

**Issue by Svetov1d** [TheHCJ/Quacker#46]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.2.0

### Steps to reproduce the bug

When i open Quacker there are only posts, but without profile names and profile pics
![Screenshot_2023-06-02-18-31-13-370_com thehcj quacker](https://github.com/TheHCJ/Quacker/assets/125388868/8ed04979-bf84-45d3-9058-a003c9df82f9)

### Expected behavior

Posts should have autors name and profile pic

### Actual behavior

Posts without author name and profile pic

### Affected Android/Custom ROM version

Android 11 / MIUI 12.5.6

### Affected device model

Xiaomi Redmi Note 9 (merlinnfc)

### Additional information

I've cleared cache, reinstalled app and reboot device.
None of this worked.

**Comment by TheHCJ** [comment]
Is twitter banned in your country?

**Comment by Svetov1d** [comment]
> Is twitter banned in your country?

No, it isn't. When i look at specific account i see profile name and pics
![Uploading Screenshot_2023-06-03-15-38-22-617_com.thehcj.quacker.jpg…]()

**Comment by kulych** [comment]
Hi, I had the same problem and found out there is `Activate non-confirmation bias mode` enabled in `General` settings. After deactivating, profile pictures and usernames are visible :)

I think I did not enable this mode by myself. Is it possible that it can be triggered automatically?

**Comment by Svetov1d** [comment]
> Hi, I had the same problem and found out there is `Activate non-confirmation bias mode` enabled in `General` settings. After deactivating, profile pictures and usernames are visible :)
> 
> I think I did not enable this mode by myself. Is it possible that it can be triggered automatically?

Damn!
That was it, thanks mate!
Thank you very much!
Now Quacker is superior over Fritter!
