### ISSUE TITLE
Filename of image shared out has file extension .jpe rather than .jpg or jpeg

### ISSUE THREAD

**Issue by scubajeff** [TheHCJ/Quacker#47]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v+

### Steps to reproduce the bug

1. click on image of a tweet
2. from the menu choose Share, Quacker will download the file in the background and show the share sheet
3. In the receiving app, the shared image file has a filename extension `.jpe`. This is usually OK when the file is use in Android, since most of the apps dealing with picture will resort to mimetype rather than filename extension to determine file type. But when the file is upload to a server like Nextcloud, the server will have a hard time recognizing it. BTW, when you choose Download in the menu, the downloaded file has correct extension of `.jpg`

### Expected behavior

When share image file, use a common file extension like `.jpg` or `.jpeg`

**Comment by TheHCJ** [comment]
This seems to be an issue with the package I am using for sharing. I will continue to look for a fix

**Comment by j-fbriere** [comment]
Good idea, I created a [PR](https://github.com/jonjomckay/fritter/pull/752) for Fritter.
