### ISSUE TITLE
Gaps Between Feed Loading

### ISSUE THREAD

**Issue by momobobe** [TheHCJ/Quacker#48]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.2.0

### The bug

Feed loading may leave gaps. For instance, if I opened Quacker yesterday loading the feed once, and then opening it today would only show fresh tweets within past few hours, but not those say, >10 hr (not precise) and <24 hr. Scrolling deep down to load old tweets, those older than the ever first-time loading (it's about 20 days ago for my case), is fine, but those gapped tweets (like between 3 and 5 days ago, since I didn't open the App during those days) won't appear anyway in feed.

**Comment by TheHCJ** [comment]
Turns out tweet searching via GraphQL doesn't return enough data, I will look into using the Tweet Search api which sadly only returns tweets for the last week.
