### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Mike200109** [TheHCJ/Quacker#5]
Any plans to add this app to f-droid?

**Comment by TheHCJ** [comment]
Yes, I have an open merge request on the project: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13476
I will try and resolve it when I release v3.2.1 sometime this week

**Comment by TheHCJ** [comment]
The request is ready for review and 🤞🏼 gets merged soon

**Comment by TheHCJ** [comment]
Quacker has now been added to F-Droid we just need to wait for them to build it

**Comment by licaon-kter** [comment]
fyi, since you build 3 APKs for split ABI, please distance versionCode bumps on new versions at more than 3 else versionCodes will overlap: https://gitlab.com/fdroid/fdroiddata/-/blob/9ef02413e871ae6f3fc9742a716dd98952ae155d/metadata/com.thehcj.quacker.yml#L69-L94

**Comment by TheHCJ** [comment]
Ok I'll make sure todo that in future releases

**Comment by TheHCJ** [comment]
The app is now in the Official F-Droid repo, I'll wait for it to go up on the website before I add the badge to README.md

**Comment by licaon-kter** [comment]
hey @TheHCJ remember when I said https://github.com/TheHCJ/Quacker/issues/5#issuecomment-2042511749 ?

well 3.4.0 versionCode is still too low: https://gitlab.com/fdroid/fdroiddata/-/jobs/6647384413

I've disabled autoupdate, and removed 3.4.0

**Comment by TheHCJ** [comment]
@licaon-kter Should it be ok now?

**Comment by TheHCJ** [comment]
Glad to hear it
