### ISSUE TITLE
Retweets not displaying correctly in feed

### ISSUE THREAD

**Issue by drunkhamster** [TheHCJ/Quacker#5]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TheHCJ/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TheHCJ/quacker/issues) or [closed](https://github.com/TheHCJ/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Quacker

### Affected version

3.0.0

### Steps to reproduce the bug

Go to Feed; view a tweet containing a retweeted or quoted tweet. 

### Expected behavior

The retweeted or quoted tweet displays in a box (this works correctly when viewing the same tweet via the author's page)

### Actual behavior

The retweeted or quoted tweet appears as "RT: ...", with content cut off.

### Screenshots/Screen recordings

Actual behavior (in Feed):
![image](https://github.com/TheHCJ/Quacker/assets/78958330/ca1d68cd-13f1-4bba-a824-006bc8ea1945)

Expected behavior:
![image](https://github.com/TheHCJ/Quacker/assets/78958330/915a04bb-0d2e-4f3e-a9c2-5efd978017bf)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 6

**Comment by TheHCJ** [comment]
I have also now noticed this issue, a fix is coming soon

**Comment by TheHCJ** [comment]
Fixed: https://github.com/TheHCJ/Quacker/actions/runs/5591850352
