### ISSUE TITLE
[REQ] Only show reply tweets if you follow both users.

### ISSUE THREAD

**Issue by nrgst183** [TheHCJ/Quacker#5]
In the current feed, replies to tweets from people you follow also appear in the feed, regardless if you follow both users or not. Since the regular twitter feed only shows replies to tweets if you follow both users, it'd be nice if this did the same thing. 

Also, just wanted to say, thanks for keeping the feed option available. A lot of people appreciate it.

**Comment by TheHCJ** [comment]
I will look into it 😃
