### ISSUE TITLE
Link shortners are not working as links 

### ISSUE THREAD

**Issue by Revnae** [TheHCJ/Quacker#51]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

version 2.2.0 newest bulf in actions 

### Steps to reproduce the bug

Try to tap bit.ly links but it is not working 

### Expected behavior

That it should redirect you to the link in your browser 

### Actual behavior

Nothing happens when you tap the link 

### Screenshots/Screen recordings

. 

### Logs

. 

### Affected Android/Custom ROM version

Android 13

### Affected device model

Oneplus 

### Additional information

No

**Comment by j-fbriere** [comment]
Can you give a specific example by providing the URL of a specific tweet in error.

**Comment by Revnae** [comment]
Any linkshortners like bit.ly or ift.tt all of them are broken in the newest dev build

**Comment by j-fbriere** [comment]
Should be fixed with the last [ci build](https://github.com/TheHCJ/Quacker/suites/13523622022/artifacts/743495992).
