### ISSUE TITLE
Color correction quick tile causes refresh

### ISSUE THREAD

**Issue by android-smiley** [TheHCJ/Quacker#55]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v2.2.0+2005

### Steps to reproduce the bug

1. Open App
2. Toggle Color Correction Quick Tile

### Expected behavior

Only the display color should change. 

### Actual behavior

The display color changes and at the same time, the app refreshes the feed.
This also means being returned to the feed, when browsing some profile. 

### Affected Android/Custom ROM version

Android 13 (TQ2A.230505.002.2023060700)/ GrapheneOS

### Affected device model

Pixel 7 Pro

**Comment by TheHCJ** [comment]
I think this is more of a flutter issue than a Quacker one

**Comment by TheHCJ** [comment]
> This may well be. Under which keyword could I report this upstream?

I wouldn't know, maybe under the [Skia]
