### ISSUE TITLE
"Update available" notification even on latest 2.2.1 version

### ISSUE THREAD

**Issue by FoxP** [TheHCJ/Quacker#56]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.2.1

### Steps to reproduce the bug

Download, install, then open latest 2.2.1 version.
See screenshot below :

![Screenshot_20230613-150024_Quacker](https://github.com/TheHCJ/Quacker/assets/16615901/eb629b83-aea5-4584-97ad-e9067a73a322)

![Screenshot_20230613-150435_Quacker](https://github.com/TheHCJ/Quacker/assets/16615901/3c90bce6-cb59-43ea-a671-a54376290bff)

Apk attached to 2.2.1 release may not be up-to-date ?

https://github.com/TheHCJ/Quacker/releases/download/v2.2.1/quacker-v2.2.1.apk

### Affected Android/Custom ROM version

Android 11, LineageOS ROM

### Affected device model

Poco X3 Pro

**Comment by TheHCJ** [comment]
I look into it, for now just disable checking for updatesf

**Comment by EdoSecco** [comment]
I think the problem is that after the installation, the number of version is still 2.2.0 instead of 2.2.1 so the system itself detects as if it is a previous version.

**Comment by j-fbriere** [comment]
@TheHCJ The [PR](https://github.com/TheHCJ/Quacker/pull/57) I have made was meant for the release.yml workflow to be executed only when a git tag is pushed.
I didn't take into account the case when the release.yml workflow is executed manually.
I will adjust the script accordingly.

**Comment by j-fbriere** [comment]
The release.yml workflow has been fixed for a manual run, see PR #66.

The better approach is not to run this workflow manually though but instead to push a git tag.

By pushing git tags, the released artifacts are always aligned with the git tags of the code, which is important.
