### ISSUE TITLE
Error on deleted tweet which still exist in cached feed

### ISSUE THREAD

**Issue by j-fbriere** [TheHCJ/Quacker#58]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v2.2.1

### Steps to reproduce the bug

1. From twitter, create a tweet.
2. Open Quacker, the feed gets filled with tweets, including the tweet just created.
3. From twitter, delete the tweet from step 1
4. In Quacker, refreshes the feeds, the tweet is still visible because its in the Quacker cache.
5. Click on the deleted tweet.

### Expected behavior

An empty page should be displayed indicating that the tweet does not exist.

### Actual behavior

An error is throwned:
![Screenshot_20230609185806_Quacker_small](https://github.com/TheHCJ/Quacker/assets/49044668/a4a9219a-7989-4f75-8da1-46be7e232890)

**Comment by TheHCJ** [comment]
Just merged you pull request thanks for the work on Quacker!
