### ISSUE TITLE
[REQ] F-Droid Release

### ISSUE THREAD

**Issue by jcperil** [TheHCJ/Quacker#6]
**Describe the problem that needs solving**
Can you add Quacker to F-Droid?

**Describe the solution you'd like**
[This is the inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) that must be met to be able to submit. More info about submitting can be [found here](https://f-droid.org/en/contribute/).

[Here is the issue tracker](https://gitlab.com/fdroid/rfp/-/issues) to request your package to be available on F-Droid. After submitting, they can assist on what is needed to be done (if anything) to get it on F-Droid.

**Comment by TheHCJ** [comment]
I have started the process of getting the app approved into F-Droid. Check it out [here](https://gitlab.com/fdroid/rfp/-/issues/2429)!

**Comment by TheHCJ** [comment]
**The app is approved into the IzzyOnDroid repo!**

It should be up at 18:00 UTC

**Comment by vyeol** [comment]
Sorry to necro this thread. Just saw the release on IzzyOnDroid, it's much appreciated.

However, the anti-features section lists "Tracks or reports your activity" as relevant and I am curious to know what kind of information exactly is being tracked/reported to where and for what purpose? Fritter doesn't have this anti-feature listed.

**Comment by grrrrr** [comment]
@vyeol https://github.com/TheHCJ/Quacker/discussions/41
