### ISSUE TITLE
ui break

### ISSUE THREAD

**Issue by vipin-2023** [TheHCJ/Quacker#65]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

quacker-v2.2.1_arm64-v8a.apk

### Steps to reproduce the bug

1. Go to groups
2. Add new group 
3. select subscription 

### Expected behavior

"OK" button inside the modal 

### Actual behavior

"OK" button outside the modal 

### Screenshots/Screen recordings

![photo_6084813059282548877_y](https://github.com/TheHCJ/Quacker/assets/109500059/59549bda-2a29-494f-b281-55cc5e5b90c9)

### Logs

OK button outside ui . Not clickable

### Affected Android/Custom ROM version

Android 9

### Affected device model

realme c1

### Additional information

Avoid low priority buttons from the row , eg:Toggle All

**Comment by j-fbriere** [comment]
This bug has already been corrected with the [latest ci build](https://github.com/TheHCJ/Quacker/actions/runs/5298496238).
You should install the [apk-arm64 file](https://github.com/TheHCJ/Quacker/suites/13676459878/artifacts/755709147) from this build.

**Comment by vipin-2023** [comment]
thank you
