### ISSUE TITLE
Permission denied when downloading media

### ISSUE THREAD

**Issue by MeFinity** [TheHCJ/Quacker#67]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v2.2.2+300002113

### Steps to reproduce the bug

1. Press an image or video media
2. Click download

### Expected behavior

Download said media

### Actual behavior

Permission denied popup

### Screenshots/Screen recordings

![Screenshot_2023-06-21-17-50-46-41](https://github.com/TheHCJ/Quacker/assets/72972952/30dded9a-a868-4146-8b5f-cfdc9d5bfaec)

### Affected Android/Custom ROM version

Android 9

### Affected device model

OPPO A12 (CPH2083)

### Additional information

I have given the app storage access

**Comment by j-fbriere** [comment]
This is not a bug.

In the settings you have set the Download handling to save to a directory on the SD card.
On Android, you cannot directly save on a SD card without being asked first.

So either you choose in the settings to set the Download handling to save to a directory on the internal storage,
or to always ask, then you'll be able to save to a directory on the SD card that you'll select from the save dialog box.

**Comment by MeFinity** [comment]
I have picked an Internal Storage as a directory though, you can see it in the error: /storage/0/emulated/Downloads/temp-fur

I will say, when i manually save it it works, i think its some bug with my device that thinks my internal storage is an sdcard.

**Comment by Waredane** [comment]
Hi, same error with v2.2.1 and v2.2.2 .
work fine with v2.2.0 .

Redmi note 9 pro.
Resurrection Remix 8.7.0 ( android 10).

**Comment by j-fbriere** [comment]
Thank you for the information.

You're right, it is a bug.

I made a PR #72 to fix it.
