### ISSUE TITLE
The keyboard hides the writing area 

### ISSUE THREAD

**Issue by franco27** [TheHCJ/Quacker#69]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/thehcj/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/thehcj/quacker/issues) or [closed](https://github.com/thehcj/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.2.2

### Steps to reproduce the bug

When I click "import from Twitter", I can't use "paste" because the keyboard is shown and hides the writing area (an input field).

And I can't see what I'm writing because the keyboard is in front. I have to write blind. See screenshot.

### Expected behavior

That the keyboard appears, below the writing area

### Actual behavior

The keyboard hides the writing area.
![IMG_20230621_231656](https://github.com/TheHCJ/Quacker/assets/31793920/4834dc8b-7f42-4d75-82b8-69e91bdc9330)

The keyboard used is the Google keyboard .

**Comment by TheHCJ** [comment]
https://github.com/jonjomckay/fritter/issues/688
