### ISSUE TITLE
Instance error when trying to view user's tweet

### ISSUE THREAD

**Issue by CT-Murasaki** [TheHCJ/Quacker#77]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TheHCJ/Quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TheHCJ/Quacker/issues) or [closed](https://github.com/TheHCJ/Quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Quacker

### Affected version

v2.2.2+300001113

### Steps to reproduce the bug

When I try to view a user's tweet, I get an Instance error as shown in the attached image.
I tried various users, but the same error occurred, so I don't think it is a specific condition.
The followers and followers columns and lists were displayed without any problems.

### Expected behavior

Originally, tweets would appear like this. (This tweet column is viewed from the list)
![Screenshot_20230630-120104](https://github.com/TheHCJ/Quacker/assets/84951727/d31a84e2-1d82-4e61-a980-e13c456f78be)

### Actual behavior

An error occurs as shown in the image and the tweet is not displayed.
![Screenshot_20230630-115707](https://github.com/TheHCJ/Quacker/assets/84951727/990dc77e-6ec0-4151-bd10-62d03d1538bf)
![Screenshot_20230630-115709](https://github.com/TheHCJ/Quacker/assets/84951727/d9e6a2f0-2d62-45f7-a13a-339dc466c2eb)
![Screenshot_20230630-115712](https://github.com/TheHCJ/Quacker/assets/84951727/075f69b0-89b4-4d5a-8618-759958707c79)

However, there was no problem with the follow and follower fields.
![Screenshot_20230630-115714](https://github.com/TheHCJ/Quacker/assets/84951727/798600e3-80eb-488e-b6d3-c7ae4d434e00)
![Screenshot_20230630-115819](https://github.com/TheHCJ/Quacker/assets/84951727/4fed0a42-42fa-4554-a09c-735b3ca67a2d)

### Affected Android/Custom ROM version

Android13

### Affected device model

pixel7pro

**Comment by TheHCJ** [comment]
Sorry to say it but it looks like the end, I will make a post on this soon!
https://github.com/jonjomckay/fritter/issues/756
