### ISSUE TITLE
Bugs and missing features

### ISSUE THREAD

**Issue by AndiDink00x** [TheHCJ/Quacker#9]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TheHCJ/quacker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TheHCJ/quacker/issues) or [closed](https://github.com/TheHCJ/quacker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Quacker

### Affected version

Latest ci build 4.0.0 beta 1 - https://github.com/TheHCJ/Quacker/commit/d0189748a12f43b8ab5073f2de275993e83a2a85

### Steps to reproduce the bug

Happy to see the app being up and runnin' after API changes but im gonna address some bugs and features which i think are important and some of them where already present on 3.0 before the changes in the API

top most important (for me):

1.  Stop refreshing feed after tab switch
2.  Stop reentering same tweet indefinitely
3.  Display blue checks in feed
4.  Make comment button in feed's tweets visible
5.  Keep position of timeline after app restart/refresh (like squawker)
6.  Add searching in subscriptions
7.  Add option to hide either replies or retweets
8.  Make long tweets in feed entirely visible
9.  Make tweet rectangle windows little more visible in amoled theme

I dont know if the problem with missing tweets is still present (because i deleted my twitter acc and cant chenk it) but if the problem persists are you gonna plan in the future to make a switch using Nitter's API ?

### Affected Android/Custom ROM version

Android 12 / Lineage 19.1

### Affected device model

Poco X3 Pro

**Comment by TheHCJ** [comment]
Could you create seperate issues as it would make it easier to track the progress made on fixing them!

**Comment by AndiDink00x** [comment]
@TheHCJ Of course
